/* 
   Legacy local configuration generator (not used by Pages builds)
   Generates config.local.js from environment variables
   
   Current Cloudflare Pages settings are documented in ../../DEPLOYMENT.md.
   Use npm run build; deployed configuration comes from /api/config.
*/

const fs = require('fs');
const path = require('path');

// Resolve from repo root (works regardless of cwd)
const repoRoot = path.resolve(__dirname, '..');
const outPath = path.join(repoRoot, 'src', 'config.local.js');

// Read env vars (with sensible defaults for public APIs)
const vars = {
  DIGITRANSIT_URL:     process.env.DIGITRANSIT_URL     || 'https://api.digitransit.fi/routing/v2/hsl/gtfs/v1',
  DIGITRANSIT_GEO_URL: process.env.DIGITRANSIT_GEO_URL || 'https://api.digitransit.fi/geocoding/v1/search',
  DIGITRANSIT_REV_URL: process.env.DIGITRANSIT_REV_URL || 'https://api.digitransit.fi/geocoding/v1/reverse',
  TRANSITOUS_URL:      process.env.TRANSITOUS_URL      || 'https://api.transitous.org/api/v5/plan',
  DT_API_KEY:          process.env.DT_API_KEY          || '',
  NOMINATIM_REV:       process.env.NOMINATIM_REV       || 'https://nominatim.openstreetmap.org/reverse?format=json&zoom=18&addressdetails=1',
  NOMINATIM_VB:        process.env.NOMINATIM_VB        || '24.0,60.8,25.8,59.8',
  HF_TOKEN_KEY:        process.env.HF_TOKEN_KEY        || '', // share-link encryption key
};

// Log which vars came from env vs defaults
console.log('[build-secrets] Environment variable status:');
for (const [k, v] of Object.entries(vars)) {
  const fromEnv = !!process.env[k];
  const display = k === 'DT_API_KEY' && v ? v.slice(0, 6) + '…' : (v || '(empty)');
  console.log(`  ${fromEnv ? '✓ ENV' : '⚠ DEF'}  ${k} = ${display}`);
}

const config = `/* Auto-generated by build-secrets.js – do not edit or commit */
export const DIGITRANSIT_URL     = '${vars.DIGITRANSIT_URL}';
export const DIGITRANSIT_GEO_URL = '${vars.DIGITRANSIT_GEO_URL}';
export const DIGITRANSIT_REV_URL = '${vars.DIGITRANSIT_REV_URL}';
export const TRANSITOUS_URL      = '${vars.TRANSITOUS_URL}';
export const DT_API_KEY          = '${vars.DT_API_KEY}';
export const NOMINATIM_REV       = '${vars.NOMINATIM_REV}';
export const NOMINATIM_VB        = '${vars.NOMINATIM_VB}';
export const HF_TOKEN_KEY        = '${vars.HF_TOKEN_KEY}';
`;

fs.writeFileSync(outPath, config, 'utf8');
console.log(`[build-secrets] ✓ Written ${outPath}`);
console.log(`[build-secrets] ✓ File size: ${fs.statSync(outPath).size} bytes`);

