import {
  SquaresFour,
  MapPin,
  PlusCircle,
  PencilSimple,
  CalendarBlank,
  Moon,
  Star,
  Heart,
  EnvelopeSimple,
  ListBullets,
  Buildings,
  ForkKnife,
  Tote,
  PlayCircle,
  Palette,
  SlidersHorizontal,
  X,
  List,
  ArrowUpRight,
  ArrowRight,
  CaretLeft,
  CaretRight,
  MagnifyingGlass,
  SidebarSimple,
  SignOut,
  ArrowClockwise,
  CheckCircle,
  FunnelSimple,
  Rows,
  GlobeHemisphereWest,
  ShieldCheck,
  Command,
  Clock,
  Sun,
} from "@phosphor-icons/react";

const wrap = (Component) =>
  function Icon({ size = 18, ...props }) {
    return (
      <Component size={size} weight="regular" aria-hidden="true" {...props} />
    );
  };
export const Icons = Object.fromEntries(
  Object.entries({
    dashboard: SquaresFour,
    pin: MapPin,
    plusCircle: PlusCircle,
    pencil: PencilSimple,
    calendar: CalendarBlank,
    moon: Moon,
    star: Star,
    heart: Heart,
    mail: EnvelopeSimple,
    list: ListBullets,
    building: Buildings,
    utensils: ForkKnife,
    bag: Tote,
    play: PlayCircle,
    palette: Palette,
    settings: SlidersHorizontal,
    arrowUpRight: ArrowUpRight,
    arrowRight: ArrowRight,
    left: CaretLeft,
    right: CaretRight,
    search: MagnifyingGlass,
    sidebar: SidebarSimple,
    signOut: SignOut,
    refresh: ArrowClockwise,
    check: CheckCircle,
    filter: FunnelSimple,
    rows: Rows,
    globe: GlobeHemisphereWest,
    shield: ShieldCheck,
    command: Command,
    clock: Clock,
    sun: Sun,
  }).map(([key, component]) => [key, wrap(component)]),
);
export const CloseIcon = wrap(X);
export const HamburgerIcon = wrap(List);
