import { useEffect, useRef, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useWebsiteTeam, useWebsiteMutation } from '../api/website.js';
import { LoadingState } from '../components/QueryState.jsx';
import WebsitePageHeader, { WebsiteError } from '../components/WebsitePageHeader.jsx';
import { useToast } from '../components/Toast.jsx';
import { Icons, CloseIcon } from '../icons.jsx';
import useUnsavedChanges from '../components/useUnsavedChanges.js';

const EMPTY={name:'',email:'',position:'',description:'',location:'',status:'active',order:0};
function PersonEditor({person,onClose,onSaved}) {
  const [draft,setDraft]=useState({...EMPTY,...person});
  const save=useWebsiteMutation('save-person','website-team');
  const dialog=useRef(null);const toast=useToast();
  const dirty=JSON.stringify(draft)!==JSON.stringify({...EMPTY,...person});
  useUnsavedChanges(dirty);
  useEffect(()=>{const el=dialog.current;el.showModal();return ()=>el.close();},[]);
  function close(){if(save.isPending)return;if(!dirty||window.confirm('Discard the changes to this team member?'))onClose();}
  function submit(event){event.preventDefault();const nextPerson={name:draft.name.trim(),email:draft.email.trim(),position:draft.position.trim(),description:draft.description.trim(),location:draft.location.trim(),status:draft.status,order:Number(draft.order)};save.mutate({id:person.id,revision:person.revision||0,person:nextPerson},{onSuccess:result=>{onSaved({...nextPerson,id:result.id||person.id,revision:result.revision||((person.revision||0)+1)});toast('Team member saved. The website updates within a minute.');onClose();},onError:error=>toast(error.message,'error')});}
  return <dialog ref={dialog} className="website-editor-dialog" aria-labelledby="person-editor-title" onCancel={e=>{e.preventDefault();close();}}><form onSubmit={submit}><header><div><div className="eyebrow">WEBSITE TEAM</div><h2 id="person-editor-title">{person.id?'Edit team member':'Add team member'}</h2></div><button className="icon-button" type="button" aria-label="Close editor" onClick={close}><CloseIcon/></button></header><fieldset disabled={save.isPending}><div className="website-person-fields">{[{key:'name',label:'Full name',max:120},{key:'position',label:'Role or position',max:160},{key:'email',label:'Public email',type:'email',max:254},{key:'location',label:'Location',max:160}].map(field=><div className="pp-field" key={field.key}><label htmlFor={`person-${field.key}`}>{field.label}</label><input autoFocus={field.key==='name'} id={`person-${field.key}`} type={field.type||'text'} required={field.key==='name'} maxLength={field.max} value={draft[field.key]} onChange={e=>setDraft({...draft,[field.key]:e.target.value})}/></div>)}<div className="pp-field website-field-wide"><label htmlFor="person-description">Short biography</label><textarea id="person-description" rows={4} maxLength={1200} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></div><div className="pp-field"><label htmlFor="person-status">Website visibility</label><select id="person-status" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="active">Active · visible on website</option><option value="inactive">Inactive · hidden from website</option></select></div><div className="pp-field"><label htmlFor="person-order">Display order</label><input id="person-order" type="number" min={0} max={10000} required value={draft.order} onChange={e=>setDraft({...draft,order:e.target.value})}/><small className="pp-field-hint">Lower numbers appear first.</small></div></div></fieldset>{save.error&&<p className="pp-error-text" role="alert">{save.error.message}</p>}<footer><p>Active profiles and their email addresses are public.</p><button type="button" className="pp-btn" onClick={close} disabled={save.isPending}>Cancel</button><button type="submit" className="pp-btn pp-btn-primary" disabled={save.isPending}>{save.isPending?'Saving…':'Save team member'}</button></footer></form></dialog>;
}

export default function WebsiteTeamPage() {
  const query=useWebsiteTeam();const remove=useWebsiteMutation('delete-person','website-team');const toast=useToast();
  const queryClient=useQueryClient();
  const [editing,setEditing]=useState(null);const [search,setSearch]=useState('');const [status,setStatus]=useState('all');
  function mergeSavedPerson(saved) {
    queryClient.setQueryData(['website-team'], current => {
      const people=Array.isArray(current?.people)?current.people:[];
      const exists=people.some(person=>person.id===saved.id);
      const nextPeople=exists?people.map(person=>person.id===saved.id?{...person,...saved}:person):[...people,saved];
      return {...(current||{}),success:true,people:nextPeople};
    });
    query.refetch();
  }
  const people=(query.data?.people||[]).filter(person=>`${person.name} ${person.position} ${person.email}`.toLowerCase().includes(search.toLowerCase())&&(status==='all'||person.status===status)).sort((a,b)=>a.order-b.order);
  return <div className="pp-page"><WebsitePageHeader title="Website team" description="Introduce the people behind the collective. Changes are saved to your existing team directory."><button className="pp-btn pp-btn-primary" onClick={()=>setEditing(EMPTY)} disabled={!query.data}><Icons.plusCircle size={16}/>Add team member</button></WebsitePageHeader><WebsiteError query={query}/>{query.isLoading&&<LoadingState/>}{query.data&&<><div className="website-collection-toolbar"><div className="table-search-wrap"><Icons.search size={16}/><input className="pp-table-search" type="search" aria-label="Search team members" placeholder="Search the team…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Team visibility" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Everyone</option><option value="active">Active</option><option value="inactive">Inactive</option></select><span>{people.length} team members</span><button className="pp-btn" onClick={()=>query.refetch()} disabled={query.isFetching}>Refresh</button></div><div className="website-people-grid">{people.map(person=><article className="website-person-card" key={person.id}><div className="website-person-top"><span className="website-person-avatar">{person.name.split(/\s+/).map(part=>part[0]).slice(0,2).join('')}</span><span className={`pp-badge ${person.status==='active'?'pp-badge-yes':'pp-badge-pending'}`}>{person.status==='active'?'Visible':'Hidden'}</span></div><h2>{person.name}</h2><p className="website-person-role">{person.position||'Role not added'}</p><p className="website-person-bio">{person.description||'Add a short introduction for website visitors.'}</p><div className="website-person-meta"><span><Icons.mail size={14}/>{person.email||'No public email'}</span>{person.location&&<span><Icons.pin size={14}/>{person.location}</span>}</div><footer><span>Order {person.order||0}</span><button className="pp-btn" onClick={()=>setEditing(person)}><Icons.pencil size={14}/>Edit</button><button className="pp-btn pp-btn-delete" disabled={remove.isPending} onClick={()=>{if(window.confirm(`Remove ${person.name} from the team directory? You can instead edit their visibility to hide them.`))remove.mutate({id:person.id,revision:person.revision},{onSuccess:()=>toast('Team member removed'),onError:error=>toast(error.message,'error')});}}>Remove</button></footer></article>)}</div>{!people.length&&<div className="inline-empty"><Icons.building size={28}/><strong>{query.data.people.length?'No matching team members':'Introduce your team'}</strong><span>{query.data.people.length?'Try a different search or visibility filter.':'Add your first team member to display them on the website.'}</span></div>}</>}{editing&&<PersonEditor person={editing} onClose={()=>setEditing(null)} onSaved={mergeSavedPerson}/>}</div>;
}
