// MapLibre GL style definition for the Helsinki base map
export const HSL_STYLE = {
  version: 8,
  name: "HSL Helsinki",
  sources: {
    openmaptiles: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
      attribution:
        '&copy; <a href="https://openfreemap.org">OpenFreeMap</a> <a href="https://www.openmaptiles.org/">© OpenMapTiles</a> <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap</a>',
    },
    "terrain-dem": {
      type: "raster-dem",
      tiles: [
        "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
      ],
      encoding: "terrarium",
      tileSize: 256,
      maxzoom: 15,
    },
  },
  glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  layers: [
    {
      id: "background",
      type: "background",
      paint: {
        "background-color": [
          "interpolate",
          ["linear"],
          ["zoom"],
          7,
          "#d3e3bb",
          9,
          "#f0f1f2",
        ],
      },
    },
    {
      id: "landcover_grass",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", "class", "grass"],
      paint: { "fill-color": "#ddeacd", "fill-opacity": 0.9 },
    },
    {
      id: "landcover_wood",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", "class", "wood"],
      paint: { "fill-color": "#d0e3b8", "fill-opacity": 0.9 },
    },
    {
      id: "landcover_farmland",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", "class", "farmland"],
      paint: { "fill-color": "#e3ecc5", "fill-opacity": 0.7 },
    },
    {
      id: "landcover_sand",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", "class", "sand"],
      paint: { "fill-color": "#e0dfcc" },
    },
    {
      id: "landcover_ice",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", "class", "ice"],
      paint: { "fill-color": "#eef5f9" },
    },
    {
      id: "landuse_residential",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: ["in", "class", "residential", "suburbs"],
      paint: { "fill-color": "#eceae5", "fill-opacity": 0.5 },
    },
    {
      id: "landuse_industrial",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: ["==", "class", "industrial"],
      paint: { "fill-color": "#ede6e3" },
    },
    {
      id: "landuse_hospital",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: ["==", "class", "hospital"],
      paint: { "fill-color": "#fbe6e0" },
    },
    {
      id: "landuse_school",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: ["in", "class", "school", "university", "kindergarten"],
      paint: { "fill-color": "#f9f4d2" },
    },
    {
      id: "landuse_cemetery",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: ["==", "class", "cemetery"],
      paint: { "fill-color": "#cbdeb4", "fill-outline-color": "#b8d19b" },
    },
    {
      id: "landuse_pitch",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      minzoom: 13,
      filter: ["==", "class", "pitch"],
      paint: { "fill-color": "#cde0b6", "fill-outline-color": "#acc78b" },
    },
    {
      id: "park",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "park",
      paint: {
        "fill-color": "#dceacc",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0.6, 12, 0.8],
      },
    },
    {
      id: "waterway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["in", "class", "canal", "river", "stream"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#bee4f8",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          8,
          0.5,
          20,
          15,
        ],
      },
    },
    {
      id: "water",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "water",
      paint: { "fill-color": "#bee4f8" },
    },
    {
      id: "aeroway_fill",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "aeroway",
      filter: ["==", "$type", "Polygon"],
      paint: { "fill-color": "#e3e3e3" },
    },
    {
      id: "aeroway_runway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "aeroway",
      filter: ["==", "class", "runway"],
      layout: { "line-cap": "square" },
      paint: {
        "line-color": "#fff",
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          10,
          2.5,
          20,
          240,
        ],
      },
    },
    {
      id: "building_shadow",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "building",
      minzoom: 13,
      paint: {
        "fill-color": "#c2c3cc",
        "fill-translate": [2, 3],
        "fill-translate-anchor": "viewport",
      },
    },
    {
      id: "building",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "building",
      minzoom: 13,
      paint: {
        "fill-color": "#e2e4e9",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0, 14, 1],
      },
    },
    {
      id: "building_outline",
      type: "line",
      source: "openmaptiles",
      "source-layer": "building",
      minzoom: 14,
      paint: { "line-color": "#d0d2da", "line-width": 0.5 },
    },
    {
      id: "tunnel_path",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: ["all", ["==", "brunnel", "tunnel"], ["==", "class", "path"]],
      paint: {
        "line-color": "#e0e0e0",
        "line-width": 1,
        "line-dasharray": [3, 3],
      },
    },
    {
      id: "tunnel_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "brunnel", "tunnel"],
        ["in", "class", "minor", "service"],
      ],
      paint: {
        "line-color": "#f0f0f0",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          12,
          1,
          18,
          10,
        ],
      },
    },
    {
      id: "tunnel_major",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "brunnel", "tunnel"],
        [
          "in",
          "class",
          "primary",
          "secondary",
          "tertiary",
          "trunk",
          "motorway",
        ],
      ],
      layout: { "line-cap": "butt" },
      paint: {
        "line-color": "#e8e8e8",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          6,
          0.5,
          18,
          30,
        ],
        "line-dasharray": [3, 3],
      },
    },
    {
      id: "road_path",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["==", "class", "path"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#d4c6ba",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          14,
          0.5,
          20,
          4,
        ],
        "line-dasharray": [3, 2],
      },
    },
    {
      id: "road_service",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["in", "class", "minor", "service"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#fff",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          12,
          0.5,
          18,
          10,
        ],
      },
    },
    {
      id: "road_secondary_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["in", "class", "secondary", "tertiary"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#ccc",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          8,
          0.5,
          18,
          18,
        ],
        "line-gap-width": 0,
      },
    },
    {
      id: "road_secondary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["in", "class", "secondary", "tertiary"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#fff",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          8,
          0.4,
          18,
          16,
        ],
      },
    },
    {
      id: "road_primary_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["==", "class", "primary"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#ccc",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          6,
          0.3,
          18,
          24,
        ],
      },
    },
    {
      id: "road_primary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["==", "class", "primary"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#fff",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          6,
          0.2,
          18,
          22,
        ],
      },
    },
    {
      id: "road_trunk_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["==", "class", "trunk"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#f4d880",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          6,
          0.4,
          18,
          28,
        ],
      },
    },
    {
      id: "road_trunk",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["==", "class", "trunk"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#fef2c6",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          6,
          0.3,
          18,
          24,
        ],
      },
    },
    {
      id: "road_motorway_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["==", "class", "motorway"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#f4d880",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          5,
          0.4,
          18,
          34,
        ],
      },
    },
    {
      id: "road_motorway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["!=", "brunnel", "tunnel"],
        ["==", "class", "motorway"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#fef2c6",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          5,
          0.3,
          18,
          30,
        ],
      },
    },
    {
      id: "rail",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: ["==", "class", "rail"],
      paint: {
        "line-color": "#bbb",
        "line-width": ["interpolate", ["linear"], ["zoom"], 8, 0.6, 16, 3],
        "line-dasharray": [6, 4],
      },
    },
    {
      id: "bridge_minor_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "brunnel", "bridge"],
        ["in", "class", "minor", "service"],
      ],
      layout: { "line-cap": "butt" },
      paint: {
        "line-color": "#ccc",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          12,
          2,
          18,
          14,
        ],
      },
    },
    {
      id: "bridge_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "brunnel", "bridge"],
        ["in", "class", "minor", "service"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#fff",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          12,
          1,
          18,
          10,
        ],
      },
    },
    {
      id: "bridge_major_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "brunnel", "bridge"],
        [
          "in",
          "class",
          "primary",
          "secondary",
          "tertiary",
          "trunk",
          "motorway",
        ],
      ],
      layout: { "line-cap": "butt" },
      paint: {
        "line-color": "#ccc",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          6,
          1,
          18,
          36,
        ],
      },
    },
    {
      id: "bridge_major",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", "brunnel", "bridge"],
        [
          "in",
          "class",
          "primary",
          "secondary",
          "tertiary",
          "trunk",
          "motorway",
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": "#fff",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          6,
          0.5,
          18,
          30,
        ],
      },
    },
    {
      id: "admin_sub",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      filter: ["all", ["<=", "admin_level", 4], [">=", "admin_level", 3]],
      paint: {
        "line-color": "#c8b4a0",
        "line-width": 0.8,
        "line-dasharray": [4, 3],
      },
    },
    {
      id: "admin_country",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      filter: ["==", "admin_level", 2],
      paint: {
        "line-color": "#aca08c",
        "line-width": ["interpolate", ["linear"], ["zoom"], 2, 0.5, 10, 2],
      },
    },
    {
      id: "label_road",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "transportation_name",
      minzoom: 13,
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Regular"],
        "symbol-placement": "line",
        "text-size": ["interpolate", ["linear"], ["zoom"], 13, 10, 18, 15],
        "text-rotation-alignment": "map",
        "text-max-angle": 30,
      },
      paint: {
        "text-color": "#777",
        "text-halo-color": "#fff",
        "text-halo-width": 1.2,
      },
    },
    {
      id: "label_water",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "water_name",
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Italic"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 8, 12, 16, 18],
        "text-max-width": 6,
      },
      paint: {
        "text-color": "#6b9dc2",
        "text-halo-color": "rgba(255,255,255,.7)",
        "text-halo-width": 1,
      },
    },
    {
      id: "label_park",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "park",
      minzoom: 12,
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Italic"],
        "text-size": 11,
        "text-max-width": 6,
      },
      paint: {
        "text-color": "#5a8a4a",
        "text-halo-color": "#fff",
        "text-halo-width": 1,
      },
    },
    {
      id: "label_poi",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "poi",
      minzoom: 14,
      filter: ["<=", "rank", 24],
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Regular"],
        "text-size": 10,
        "text-anchor": "top",
        "text-offset": [0, 0.6],
        "text-max-width": 7,
        "text-optional": true,
        "icon-optional": true,
      },
      paint: {
        "text-color": "#666",
        "text-halo-color": "#fff",
        "text-halo-width": 1,
      },
    },
    {
      id: "label_place_village",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 10,
      filter: ["==", "class", "village"],
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Regular"],
        "text-size": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          10,
          10,
          16,
          18,
        ],
        "text-max-width": 6,
      },
      paint: {
        "text-color": "#666",
        "text-halo-color": "#fff",
        "text-halo-width": 1,
      },
    },
    {
      id: "label_place_town",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 8,
      filter: ["==", "class", "town"],
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Regular"],
        "text-size": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          8,
          12,
          16,
          20,
        ],
        "text-max-width": 6,
      },
      paint: {
        "text-color": "#555",
        "text-halo-color": "#fff",
        "text-halo-width": 1,
      },
    },
    {
      id: "label_place_city",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 14,
      filter: ["==", "class", "city"],
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Bold"],
        "text-size": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          6,
          10,
          10,
          18,
        ],
        "text-transform": "uppercase",
        "text-letter-spacing": 0.1,
      },
      paint: {
        "text-color": "#555",
        "text-halo-color": "#fff",
        "text-halo-width": 1.5,
      },
    },
    {
      id: "label_country",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 8,
      filter: ["all", ["==", "class", "country"], ["has", "iso_a2"]],
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Bold"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 3, 10, 8, 24],
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#666",
        "text-halo-color": "#fff",
        "text-halo-width": 1.5,
      },
    },
  ],
};
