import { execFileSync, execSync } from "node:child_process";
import { mkdir, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(fileURLToPath(new URL("../", import.meta.url)));
const localRoot = path.join(repoRoot, ".local-backups", "deploy-agent");

const APP_SCOPES = {
  maps: {
    label: "Maps",
    paths: ["Maps/", "shared/", "package.json", "package-lock.json"],
    checks: ["npm run build:maps", "npm run test:maps:smoke"],
  },
  website: {
    label: "Website",
    paths: ["Website/", "shared/", "package.json", "package-lock.json"],
    checks: [
      "npm run build:website",
      "npm run test:website",
      "npm run test:website:ui",
    ],
  },
  admin: {
    label: "Admin",
    paths: [
      "Admin/",
      "Maps/src/app-settings-schema.js",
      "Maps/src/app-controls-schema.js",
      "Website/assets/",
      "Website/assets/js/content-schema.mjs",
      "shared/",
      "package.json",
      "package-lock.json",
    ],
    checks: ["npm run build:admin", "npm run test:admin"],
  },
  links: {
    label: "Links",
    paths: ["Links/", "Maps/functions/_link-hub.js", "Maps/functions/api/admin.js", "Maps/migrations/0011_link_hub.sql", "Maps/migrations/0012_link_hub_content.sql", "Maps/migrations/0013_link_hub_card_overrides.sql", "Maps/migrations/0014_link_hub_optional_copy.sql", "package.json", "package-lock.json"],
    checks: ["npm run build:links", "npm run test:links"],
  },
};

const SHARED_CHECKS = ["npm run check"];

const DEPLOY_FILES = [
  "package.json",
  "package-lock.json",
  "Maps/package.json",
  "Maps/index.html",
  "Maps/manifest.json",
  "Maps/sw.js",
  "Maps/_headers",
  "Maps/_routes.json",
  "Maps/kc_logo_big.inline.svg",
  "Maps/LOGO - halal finder.svg",
  "Maps/src",
  "Maps/data",
  "Maps/functions",
  "Maps/scripts/build.mjs",
  "Maps/scripts/transit-cache.json",
  "Website/package.json",
  "Website/index.html",
  "Website/privacy-policy.html",
  "Website/robots.txt",
  "Website/_headers",
  "Website/_routes.json",
  "Website/assets",
  "Website/build",
  "Website/functions",
  "Website/scripts/build.mjs",
  "Website/tailwind.config.cjs",
  "Website/tailwind-input.css",
  "Admin/package.json",
  "Admin/index.html",
  "Admin/src",
  "Admin/vite.config.js",
  "Links/package.json",
  "Links/index.html",
  "Links/styles.css",
  "Links/app.js",
  "Links/robots.txt",
  "Links/_headers",
  "Links/_routes.json",
  "Links/functions",
  "Links/scripts/build.mjs",
  "shared",
];

const SECRET_OR_LOCAL =
  /(^|[\\/])(\.env|\.dev\.vars|config\.local\.js|node_modules|dist|\.wrangler|test-results|playwright-report)([\\/]|$)|\.(bak|backup|tmp|temp)$/i;

function git(args, options = {}) {
  return execFileSync("git", args, {
    cwd: options.cwd || repoRoot,
    encoding: "utf8",
    input: options.input,
    stdio: options.input ? ["pipe", "pipe", "pipe"] : ["ignore", "pipe", "pipe"],
    windowsHide: true,
    env: options.env ? { ...process.env, ...options.env } : process.env,
  }).trim();
}

function run(command) {
  execSync(command, { cwd: repoRoot, stdio: "inherit", windowsHide: true });
}

function changedFiles(base) {
  const files = new Set();
  try {
    git(["rev-parse", "--verify", base]);
  } catch {
    for (const file of git(["diff", "--name-only", "HEAD~1...HEAD"])
      .split(/\r?\n/)
      .filter(Boolean)) {
      files.add(file);
    }
    return [...files];
  }
  for (const file of git(["diff", "--name-only", `${base}...HEAD`])
    .split(/\r?\n/)
    .filter(Boolean)) {
    files.add(file);
  }
  for (const file of git(["diff", "--name-only"]).split(/\r?\n/).filter(Boolean)) {
    files.add(file);
  }
  for (const line of git(["status", "--short"]).split(/\r?\n/).filter(Boolean)) {
    const file = line.slice(3).replace(/^.* -> /, "");
    if (file) files.add(file);
  }
  return [...files];
}

function detectScopes(files) {
  const scopes = new Set();
  for (const file of files) {
    for (const [scope, config] of Object.entries(APP_SCOPES)) {
      if (
        config.paths.some(
          (prefix) => file === prefix.replace(/\/$/, "") || file.startsWith(prefix),
        )
      ) {
        scopes.add(scope);
      }
    }
    if (file.startsWith("tooling/") || file === ".github/prompts/deploy.prompt.md") {
      scopes.add("maps");
      scopes.add("website");
      scopes.add("admin");
      scopes.add("links");
    }
  }
  return [...scopes];
}

function deployBranchReadme() {
  return [
    "# Deployment branch",
    "",
    "This branch is generated by `npm run deploy:agent -- sync <branch>`.",
    "It intentionally contains only files Cloudflare Pages needs to build and run Maps, Website, Admin, and Links.",
    "Make source changes on `main`, then regenerate this branch.",
    "",
  ].join("\n");
}

function deployFileList() {
  const files = new Set();
  for (const item of DEPLOY_FILES) {
    const output = git(["ls-tree", "-r", "--name-only", "HEAD", "--", item]);
    for (const file of output.split(/\r?\n/).filter(Boolean)) {
      if (!SECRET_OR_LOCAL.test(file)) files.add(file);
    }
  }
  return [...files].sort();
}

async function syncBranch(branch, push) {
  if (!["preview", "deploy"].includes(branch)) {
    throw new Error("sync expects `preview` or `deploy`");
  }

  await mkdir(localRoot, { recursive: true });
  const indexPath = path.join(localRoot, `${branch}.index`);
  await rm(indexPath, { force: true });
  const env = { GIT_INDEX_FILE: indexPath };
  const files = deployFileList();

  git(["read-tree", "--empty"], { env });
  for (const file of files) {
    const entry = git(["ls-tree", "HEAD", "--", file]);
    const match = entry.match(/^(\d+)\s+blob\s+([0-9a-f]+)\t(.+)$/);
    if (!match) throw new Error(`Could not read tree entry for ${file}`);
    git(["update-index", "--add", "--cacheinfo", `${match[1]},${match[2]},${file}`], {
      env,
    });
  }

  const readmeBlob = git(["hash-object", "-w", "--stdin"], {
    input: deployBranchReadme(),
  });
  git(["update-index", "--add", "--cacheinfo", `100644,${readmeBlob},README.deploy-branch.md`], {
    env,
  });

  const tree = git(["write-tree"], { env });
  const source = git(["rev-parse", "--short", "HEAD"]);
  const commit = git(["commit-tree", tree, "-m", `Prepare ${branch} deployment tree from ${source}`]);
  git(["update-ref", `refs/heads/${branch}`, commit]);
  await rm(indexPath, { force: true });

  console.log(`${branch} now points to ${commit.slice(0, 7)} with ${files.length + 1} deployment files.`);
  if (push) git(["push", "-u", "origin", `+${branch}:${branch}`], { stdio: "inherit" });
}

async function printPlan(base) {
  const files = changedFiles(base);
  const scopes = detectScopes(files);
  console.log(`Changed files compared with ${base}: ${files.length || 0}`);
  console.log(`Deployment scopes: ${scopes.length ? scopes.join(", ") : "none"}`);
  for (const scope of scopes) {
    console.log(`${APP_SCOPES[scope].label}: ${APP_SCOPES[scope].checks.join(" && ")}`);
  }
  if (scopes.length) console.log(`Shared: ${SHARED_CHECKS.join(" && ")}`);
}

async function validate(base) {
  const scopes = detectScopes(changedFiles(base));
  const commands = new Set(SHARED_CHECKS);
  for (const scope of scopes) for (const check of APP_SCOPES[scope].checks) commands.add(check);
  if (!commands.size) {
    console.log("No deployable app changes detected.");
    return;
  }
  for (const command of commands) run(command);
}

const [command = "plan", branchOrBase, ...rest] = process.argv.slice(2);
const push = rest.includes("--push") || process.argv.includes("--push");
const base = branchOrBase && !["preview", "deploy"].includes(branchOrBase)
  ? branchOrBase
  : "main";

if (command === "plan") await printPlan(branchOrBase || "main");
else if (command === "validate") await validate(branchOrBase || "main");
else if (command === "sync") await syncBranch(branchOrBase || "preview", push);
else {
  console.log("Usage:");
  console.log("  npm run deploy:agent -- plan [base]");
  console.log("  npm run deploy:agent -- validate [base]");
  console.log("  npm run deploy:agent -- sync preview [--push]");
  console.log("  npm run deploy:agent -- sync deploy [--push]");
  process.exitCode = 1;
}
