import { execFileSync, execSync } from "node:child_process";
import {
  cp,
  mkdir,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(fileURLToPath(new URL("../", import.meta.url)));
const localRoot = path.join(repoRoot, ".local-backups", "deploy-agent");

const APP_SCOPES = {
  maps: {
    label: "Maps",
    paths: ["Maps/", "shared/", "package.json", "package-lock.json"],
    checks: ["npm run build:maps", "npm run test:maps:smoke"],
  },
  website: {
    label: "Website",
    paths: ["Website/", "shared/", "package.json", "package-lock.json"],
    checks: ["npm run build:website", "npm run test:website", "npm run test:website:ui"],
  },
  admin: {
    label: "Admin",
    paths: [
      "Admin/",
      "Maps/src/app-settings-schema.js",
      "Maps/src/app-controls-schema.js",
      "Website/assets/",
      "Website/assets/js/content-schema.mjs",
      "shared/",
      "package.json",
      "package-lock.json",
    ],
    checks: ["npm run build:admin", "npm run test:admin"],
  },
};

const SHARED_CHECKS = ["npm run check"];

const DEPLOY_FILES = [
  "package.json",
  "package-lock.json",
  "Maps/package.json",
  "Maps/index.html",
  "Maps/manifest.json",
  "Maps/sw.js",
  "Maps/_headers",
  "Maps/_routes.json",
  "Maps/kc_logo_big.inline.svg",
  "Maps/LOGO - halal finder.svg",
  "Maps/src",
  "Maps/data",
  "Maps/functions",
  "Maps/scripts/build.mjs",
  "Maps/scripts/transit-cache.json",
  "Website/package.json",
  "Website/index.html",
  "Website/privacy-policy.html",
  "Website/robots.txt",
  "Website/_headers",
  "Website/_routes.json",
  "Website/assets",
  "Website/build",
  "Website/functions",
  "Website/scripts/build.mjs",
  "Website/tailwind.config.cjs",
  "Website/tailwind-input.css",
  "Admin/package.json",
  "Admin/index.html",
  "Admin/src",
  "Admin/vite.config.js",
  "shared",
];

const SECRET_OR_LOCAL = /(^|[\\/])(\.env|\.dev\.vars|config\.local\.js|node_modules|dist|\.wrangler|test-results|playwright-report)([\\/]|$)/;

function git(args, options = {}) {
  return execFileSync("git", args, {
    cwd: options.cwd || repoRoot,
    encoding: "utf8",
    stdio: options.stdio || ["ignore", "pipe", "pipe"],
    windowsHide: true,
  }).trim();
}

function run(command) {
  execSync(command, {
    cwd: repoRoot,
    stdio: "inherit",
    windowsHide: true,
  });
}

function changedFiles(base) {
  const files = new Set();
  try {
    git(["rev-parse", "--verify", base]);
  } catch {
    for (const file of git(["diff", "--name-only", "HEAD~1...HEAD"]).split(/\r?\n/).filter(Boolean)) files.add(file);
    return [...files];
  }
  for (const file of git(["diff", "--name-only", `${base}...HEAD`]).split(/\r?\n/).filter(Boolean)) files.add(file);
  for (const file of git(["diff", "--name-only"]).split(/\r?\n/).filter(Boolean)) files.add(file);
  for (const line of git(["status", "--short"]).split(/\r?\n/).filter(Boolean)) {
    const file = line.slice(3).replace(/^.* -> /, "");
    if (file) files.add(file);
  }
  return [...files];
}

function detectScopes(files) {
  const scopes = new Set();
  for (const file of files) {
    for (const [scope, config] of Object.entries(APP_SCOPES)) {
      if (config.paths.some((prefix) => file === prefix.replace(/\/$/, "") || file.startsWith(prefix))) {
        scopes.add(scope);
      }
    }
    if (file.startsWith("tooling/") || file === ".github/prompts/deploy.prompt.md") {
      scopes.add("maps");
      scopes.add("website");
      scopes.add("admin");
    }
  }
  return [...scopes];
}

async function removeDeployTree(folder) {
  const resolved = path.resolve(folder);
  const allowed = path.resolve(localRoot);
  if (!resolved.startsWith(allowed + path.sep)) {
    throw new Error(`Refusing to clean outside ${allowed}`);
  }
  await rm(resolved, { recursive: true, force: true });
}

async function copyDeployFiles(target) {
  await mkdir(target, { recursive: true });
  for (const item of DEPLOY_FILES) {
    const source = path.join(repoRoot, item);
    if (!existsSync(source)) continue;
    await cp(source, path.join(target, item), {
      recursive: true,
      filter: (candidate) => !SECRET_OR_LOCAL.test(candidate),
    });
  }
  await writeFile(
    path.join(target, "README.deploy-branch.md"),
    [
      "# Deployment branch",
      "",
      "This branch is generated by `npm run deploy:agent -- sync <branch>`.",
      "It intentionally contains only files Cloudflare Pages needs to build and run Maps, Website, and Admin.",
      "Make source changes on `main`, then regenerate this branch.",
      "",
    ].join("\n"),
    "utf8",
  );
}

async function listFiles(folder, prefix = "") {
  const output = [];
  for (const entry of await readdir(folder, { withFileTypes: true })) {
    if (entry.name === ".git") continue;
    const relative = path.join(prefix, entry.name);
    const absolute = path.join(folder, relative);
    if (entry.isDirectory()) output.push(...await listFiles(folder, relative));
    else output.push(relative.replace(/\\/g, "/"));
  }
  return output;
}

async function assertNoForbiddenFiles(folder) {
  for (const relative of await listFiles(folder)) {
    if (SECRET_OR_LOCAL.test(relative)) {
      throw new Error(`Deployment branch contains local-only file: ${relative}`);
    }
  }
}

async function syncBranch(branch, push) {
  if (!["preview", "deploy"].includes(branch)) {
    throw new Error("sync expects `preview` or `deploy`");
  }
  const worktree = path.join(localRoot, branch);
  await mkdir(localRoot, { recursive: true });
  if (existsSync(worktree)) {
    try {
      git(["worktree", "remove", "--force", worktree]);
    } catch {
      await removeDeployTree(worktree);
    }
  }
  git(["worktree", "add", "-B", branch, worktree, "HEAD"], { stdio: "inherit" });
  for (const entry of await readdir(worktree)) {
    if (entry === ".git") continue;
    await rm(path.join(worktree, entry), { recursive: true, force: true });
  }
  await copyDeployFiles(worktree);
  await assertNoForbiddenFiles(worktree);
  git(["add", "-A"], { cwd: worktree, stdio: "inherit" });
  const porcelain = git(["status", "--short"], { cwd: worktree });
  if (!porcelain) {
    console.log(`${branch} already matches the filtered deployment tree.`);
  } else {
    const source = git(["rev-parse", "--short", "HEAD"]);
    git(
      [
        "commit",
        "-m",
        `Prepare ${branch} deployment tree from ${source}`,
      ],
      { cwd: worktree, stdio: "inherit" },
    );
  }
  if (push) git(["push", "-u", "origin", branch], { cwd: worktree, stdio: "inherit" });
  git(["worktree", "remove", "--force", worktree], { stdio: "inherit" });
}

async function printPlan(base) {
  const files = changedFiles(base);
  const scopes = detectScopes(files);
  console.log(`Changed files compared with ${base}: ${files.length || 0}`);
  console.log(`Deployment scopes: ${scopes.length ? scopes.join(", ") : "none"}`);
  for (const scope of scopes) console.log(`${APP_SCOPES[scope].label}: ${APP_SCOPES[scope].checks.join(" && ")}`);
  if (scopes.length) console.log(`Shared: ${SHARED_CHECKS.join(" && ")}`);
}

async function validate(base) {
  const scopes = detectScopes(changedFiles(base));
  const commands = new Set(SHARED_CHECKS);
  for (const scope of scopes) for (const check of APP_SCOPES[scope].checks) commands.add(check);
  if (!commands.size) {
    console.log("No deployable app changes detected.");
    return;
  }
  for (const command of commands) run(command);
}

const [command = "plan", branchOrBase, ...rest] = process.argv.slice(2);
const push = rest.includes("--push") || process.argv.includes("--push");
const base = branchOrBase && !["preview", "deploy"].includes(branchOrBase) ? branchOrBase : "main";

if (command === "plan") await printPlan(branchOrBase || "main");
else if (command === "validate") await validate(branchOrBase || "main");
else if (command === "sync") await syncBranch(branchOrBase || "preview", push);
else {
  console.log("Usage:");
  console.log("  npm run deploy:agent -- plan [base]");
  console.log("  npm run deploy:agent -- validate [base]");
  console.log("  npm run deploy:agent -- sync preview [--push]");
  console.log("  npm run deploy:agent -- sync deploy [--push]");
  process.exitCode = 1;
}
